Move neo4j docker version used in tests
Moved it to 4.2 to match <4.3 in setup.py. The issue was that a
plugin's Java JAR wasn't available, which was reported by the neo4j
docker:

Fetching versions.json for Plugin 'apoc' from https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json
Error: No jar URL found for version '4.0.12' in versions.json from 'https://neo4j-contrib.github.io/neo4j-apoc-procedures/versions.json'